### ISSUE TITLE
UI/UX Design Sketch

### ISSUE THREAD

**Issue by jpnykw** [JPNYKW/SecHack365-IoT-Safety-Test#1]
XDで作ったものを上げておきます（随時更新）
提案等あったらぜひ投げてください 🙏

**Comment by jpnykw** [comment]
## 全体
ウィンドウサイズは 1000 x 800 (width x height)  

![スクリーンショット 2019-05-14 15 22 20](https://user-images.githubusercontent.com/31243896/57675243-56fcfd00-765c-11e9-8f8a-9ea5f71d418c.png)

## 各画面（フローに沿ってます）
### ・タイトル（起動画面）のイメージ  
文章は適当にそれっぽいものを当てはめてみた

![スクリーンショット 2019-05-14 15 23 41](https://user-images.githubusercontent.com/31243896/57675248-5e240b00-765c-11e9-9069-a162a7324fff.png)

### ・ネットワーク内のIoTデバイスをリスト表示する  
デバイスを検出して表示していく  

![スクリーンショット 2019-05-14 15 23 43](https://user-images.githubusercontent.com/31243896/57675274-6d0abd80-765c-11e9-83f6-ea1f0f59f542.png)

### ・ステータスを右側に表示
スキャン結果を視覚的に表示する  

| 色 | 状態 |
| - | - |
| 緑 | 正常 |
| 赤 | 警告 |
| 灰 | スキャン中 |

![スクリーンショット 2019-05-14 15 23 45](https://user-images.githubusercontent.com/31243896/57675286-772cbc00-765c-11e9-93d1-5c35142c2e67.png)

### ・スキャン終了（結果表示前）
終了したことをわかりやすくするため

![スクリーンショット 2019-05-14 15 23 46](https://user-images.githubusercontent.com/31243896/57675290-80b62400-765c-11e9-9cb4-66c967cbc686.png)

### ・リザルト
結果を表示する  
下部ボタンを押下する事で再診断できる  
![スクリーンショット 2019-05-14 15 23 47](https://user-images.githubusercontent.com/31243896/57675310-8f9cd680-765c-11e9-8c69-2f3af4d8ebe1.png)

**Comment by onsd** [comment]
わかりやすくていいと思います
