### ISSUE TITLE
Asked the password when I run device_scan.py

### ISSUE THREAD

**Issue by jpnykw** [JPNYKW/SecHack365-IoT-Safety-Test#3]
ローカルで`index.js`を作り、`device_scan.py`を実行してみたのですが、  
passwordを聞かれました。これは何と入力すればいいのでしょうか？

![スクリーンショット 2019-05-14 14 27 55](https://user-images.githubusercontent.com/31243896/57672811-99224080-7654-11e9-8685-fbb9170a18f8.png)

**Comment by onsd** [comment]
nmapの実行に管理者権限が必要なため、端末のパスワードをいれてあげてください。

もしくはsudo node index とかやるかですかね...?

**Comment by jpnykw** [comment]
あ、なるほど、理解しました。ありがとうございます。
